#pragma once

// Image resources generated by assets_src/gen_images.py (LVGLImage.py --ofmt C).
// The bg_shizue.c / bubble_bg.c files are compiled as C, so declare the symbols
// with C linkage to avoid C++ name mangling mismatches at link time.

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

// 240x320 RGB565 full-screen background (Animal Crossing Isabelle / 西施惠).
extern const lv_image_dsc_t bg_shizue;

// 232x96 RGB565A8 speech bubble background (with alpha).
extern const lv_image_dsc_t bubble_bg;

#ifdef __cplusplus
}
#endif
